import Navbar from './components/navbar/Navbar'
import './globals.css'
import { League_Spartan } from 'next/font/google'

const inter = League_Spartan({ subsets: ['latin'] })

export const metadata = {
  title: 'Invoice App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
